### PR TITLE
Composition without intercept

### PR DESCRIPTION
**Pull request by JeroenVinke**

### CODE REVIEW

**Comment by adriatic** [comment]
This is the the method to be used in the Alpha release, right? We need to test it well (including engaging @souldrinker to do that) before we announce it to the world. That tells me that we cannot release it (create the release bits **and** release announcement in Kendo's discussion thread) before sometime next week

**Comment by JeroenVinke** [comment]
There hasn't been __that__ many changes. The only thing I can think of is that we renamed `widget` to`kWidget` (so we follow the conventions used for other bindable properties, `k-`) and that we removed the function proxies, so you now have to call functions on the original Kendo control (which we exposed). So from the outside world, not much has changed, most changes were internal.

**Comment by adriatic** [comment]
Even better then - being distracted by just a few days, I lost the grasp of issues :-(

**Comment by Souldrinker** [comment]
I thought I could give some feedback here after upgrading to the 0.1.0 version, which worked fine. All is up and running again for me on the new version.

As Jeroen mentioned the function proxies were removed and the grid.widget changed name to kWidget, but the kWidget doesn't exist in the d.ts file. So to get stuff working I had to add ```kWidget: kendo.ui.Grid;``` to the Grid class in your d.ts file. I suppose you might not want to include stuff from the kendo.*.d.ts files since the users might use the core kendo without grid stuff, but maybe you should then declare it as any or be very clear to us TypeScript users that kWidget needs to be added to the d.ts file?

Then for most of the stuff I used on the grid I just added kWidget, like ```this.grid.hideColumn``` changed to ```this.grid.kWidget.hideColumn``` etc.

But in some cases maybe either Kendo is too strict in its typings or maybe I'm just not getting how to use stuff correctly.

For example where I previously did this:
```
const selected = this.grid.select();
for (let i = 0; i < selected.length; i++) {
    ids.push(this.grid.dataItem(selected[i]).id);
}
```
...I had to change the content of the for loop to this:
```
const dataItem: any = this.grid.kWidget.dataItem(selected[i]);
ids.push(dataItem.id);
```
...since dataItem returns an ObservableObject which doesn't include the properties on my object (in this case the id).

Another example where I had to change the types kendo sets to any is here:
```
this.grid.widget.dataSource._data.forEach(v => v.logStatusCss = "disabled");
```
...where I had to change my code to this:
```
this.grid.kWidget.dataSource.data().forEach((v: VehicleListItem) => v.logStatusCss = "disabled");
```
...since _data isn't available in the Telerik typings and the data() returns a kendo.data.ObservableArray whose foreach method returns an Object rather than any, thus I have to cast it to the correct type (or any).

But I suppose I can live with that and as I said everything seems to run fine with this version (and kendo 2016.1.118)

**Comment by JeroenVinke** [comment]
@Souldrinker Thanks for your feedback :)

We changed `widget` to `kWidget` so that we could expose this via the HTML api.

For example, if you use this code:

```
<k-grid k-widget.bind="grid"></k-grid>
```

the `grid` property on your view-model will be the original Kendo grid, on which you can do `this.grid.dataSource.data()` for example.

**Comment by Souldrinker** [comment]
Ah, Monday morning and too little coffee. That was much nicer and also seem to work fine :-)

**Pull request merged**
